INCLUDES=-Isrc/common

FIL_BUILD_COMMAND=$(CC) -O2 -g -fPIC -shared $$(pkg-config glib-2.0 opendiamond --cflags) -m32 -o $@ $< $(CPPFLAGS) $(CFLAGS) $(INCLUDES)

all: src/filter/libfil_euclidian.so src/filter/libfil_boostldm.so src/filter/libfil_qaldm.so src/filter/libfil_visual.so

clean:
	$(RM) src/filter/libfil_euclidian.so src/filter/libfil_boostldm.so src/filter/libfil_qaldm.so src/filter/libfil_visual.so

src/filter/libfil_euclidian.so: src/filter/fil_euclidian.c src/filter/fil_euclidian.h src/common/roi_features.h
	$(FIL_BUILD_COMMAND)
src/filter/libfil_boostldm.so: src/filter/fil_boostldm.c src/filter/fil_boostldm.h src/common/roi_features.h
	$(FIL_BUILD_COMMAND)
src/filter/libfil_qaldm.so: src/filter/fil_qaldm.c src/filter/fil_qaldm.h src/common/roi_features.h
	$(FIL_BUILD_COMMAND)
src/filter/libfil_visual.so: src/filter/fil_visual.c src/filter/fil_visual.h src/common/upmc_features.h
	$(FIL_BUILD_COMMAND)
